import enum

class State(enum.Enum):
    ACCELERATING = "ACCELERATING"
    READY = "READY"
    NOTHING = "NOTHING"
    TURNING_RIGHT = "TURNING_RIGHT"
    TURNING_LEFT = "TURNING_LEFT"
    HIT_MUD = "HIT_MUD"
    DECELERATING= "DECELERATING"
    PICKED_UP_POWERUP = "PICKED_UP_POWERUP"
    USED_BOOST = "USED_BOOST"
    USED_OIL = "USED_OIL"
    HIT_OIL = "HIT_OIL"
    FINISHED = "FINISHED"


